## YAML Template.
---
springdoc:
  swagger-ui:
    path: /swagger.html
    enabled: true
server:
  port: 8081

custom:
  activeProfileName: local
  
spring:
  application:
    name: customer
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
        ddl-auto: update
  datasource:
    url: jdbc:h2:mem:customerdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enable: true
  sql:
    init:
      mode: always
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init:
              ScriptUtils: DEBUG